### ISSUE TITLE
Add dependency: File::Find::Rule

### ISSUE THREAD

**Issue by poti1** [SBECK-github/Locale-Codes#17]
I tried to install your module on my termux, but it failed (originally) until I manually installed: `File::Find::Rule`.

Does that perhaps need to be added as a dependency?

**Comment by SBECK-github** [comment]
I'm not familiar with termux (beyone what it does... but never used it).

File::Find::Rule is NOT a dependency of Locale::Codes, but I wonder if it's a dependency of whatever tool termux is using to install modules?  In that case I would expect it to be installed as a prereq to whatever tool requires it.

If you can provide any evidence that it is actually Locale::Codes that (somehow) requires it, I'll add it as a dependency, but I suspect it's some other tool/library that has that dependency.

**Comment by poti1** [comment]
Please take a look at (I think) your test:
https://github.com/SBECK-github/Locale-Codes/blob/master/t/_version.t

On line 27, the test assumes that `File::Find::Rule` is already installed.

**Comment by SBECK-github** [comment]
The _version.t test (and the _pod.t and _pod_coverage.t tests) are only designed to be run by a person releasing a new version of the module.  They are not generally run as part of the tests for a person installing the module.  Each has a block near the start:

   unless ($ENV{RELEASE_TESTING}) {
      $ti->skip_all('Author tests not required for installation (set RELEASE_TESTING to test)');

which says that these tests are skipped unless the environment variable RELEASE_TESTING is set.  As a general rule, that variable should NOT be set.

Since these tests are not run, I explicitly exclude them from the list of dependancies.

So, have you got the environment variable set?  If so, please try unsetting it and installing it.  If it is NOT set... then I'm a bit baffled because there really should not be a dependency.

**Comment by SBECK-github** [comment]
However, good call on your find.  It's been so many years since I created the _version.t file (I use it in all of my modules) that I'd forgotten about this decision.  So it was a good reminder.

**Comment by poti1** [comment]
Just tried installing it again.
i see what you mean.
```
t/_pod.t ........... ok
t/_pod_coverage.t .. ok
t/_version.t ....... Can't locate File/Find/Rule.pm in @INC (you may need to install the File::Find::Rule module) (@INC entries checked: /data/data/com.termux/files/home/.cpanm/work/1693941007.21575/Test-Inter-1.10/t /data/data/com.termux/files/home/.cpanm/work/1693941007.21575/Test-Inter-1.10/lib /data/data/com.termux/files/home/.cpanm/work/1693941007.21575/Test-Inter-1.10/blib/lib /data/data/com.termux/files/home/.cpanm/work/1693941007.21575/Test-Inter-1.10/blib/arch /data/data/com.termux/files/usr/lib/perl5/site_perl/5.38.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.38.0 /data/data/com.termux/files/usr/lib/perl5/5.38.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.38.0 .) at t/_version.t line %.
```

**Comment by poti1** [comment]
Since I started a cpan repo, I set this in my `.bashrc` file:
```
export RELEASE_TESTING=1
```

How should I best set this variable automatically, but only when in my personal cpan repo folder? 🤔

**Comment by tgape** [comment]
Maybe both of you could change the name of the environment variable to specify what project you do release testing on rather than simply asserting that you're release testing presumably everything?

I could be off base here but this feels like a standard practice we all get wrong.

That said, the solution I went with before was to set it in my .git/hooks/pre-commit script on the prove command line itself.  This is very targeted but I have to show everyone on the team how it's done and I even get questions from people later.  "Hey Ed, I found a syntax error in your pre-commit script.  It's missing a semicolon after RELEASE_TESTING=1 and before prove.  Also for some reason my pre-commit script stopped running the release tests.". Ugh.

Sep 5, 2023 3:19:15 PM poti1 ***@***.***>:

**Comment by SBECK-github** [comment]
I agree with tgape .  I've been using RELEASE_TESTING (seemed to be standard practice when I first set that up many many years ago), but the suggestion to use a different environment variable makes a great deal of sense.

I will convert to using a variable which will incorporate the module name in it, and which won't be accidentally reused, which will solve the problem we're seeing here.

I'll add a comment later when this is done.

**Comment by poti1** [comment]
I tried and was able to install `Locale::Codes` when `RELEASE_TESTING` is not set.

I think therefore we can close this issue card.

**Comment by SBECK-github** [comment]
I've modified all of the files (in all of my modules) to use a distribution specific variable (in this case Locale_Codes_RELEASE_TESTING) so this problem will be resolved with the next release.  I don't feel that this merits a release, so the next release is scheduled for Dec 1.

**Comment by poti1** [comment]
Thanks for looking into this 🙂
